server:
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first:
      path: /first-service/**
      url: http://localhost:8081
    second:
      path: /second-service/**
      url: http://localhost:8082

logging:
  level:
    root: info
    com:
      example:
        demo:
          filter: info